### ISSUE TITLE
Trojan:Win32/Azden.A!c

### ISSUE THREAD

**Issue by subtleazn** [georg-jung/PfxCreator#1]
Your app is detected by windows defender as a severe trojan and quarantined. Trojan:Win32/Azden.A!c

Still tried using it tho, i get an error while exporting the certificate.

**Comment by georg-jung** [comment]
I noticed this too and submitted the file to Microsoft for analysis. Their online test did not recognize the file as malware plus [VirusTotal has no single detection too](https://www.virustotal.com/gui/url/b1c69838ab50697088fc4da7a92839bb6413ef072005fb23b7a9c32b471793a1/detection), so I hope this is a temporary problem.

Could you open a seperate issue regarding the export error and provide some more details? Thanks in advance.
